import $ from 'jquery';
import  'bootstrap/dist/css/bootstrap.min.css'
import  'font-awesome/css/font-awesome.min.css'
import  'nprogress/nprogress.css'
import  'iCheck/skins/flat/green.css'
import  'bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css'
import  'jqvmap/dist/jqvmap.min.css'
import  'bootstrap-daterangepicker/daterangepicker.css'
import  'animate.css/animate.min.css'
import  'bootstrap/dist/js/bootstrap.min.js'
import  'fastclick/lib/fastclick.js'
import  'nprogress/nprogress.js'
import  'Chart.js/dist/Chart.min.js'
import  'gauge.js/dist/gauge.min.js'
import  'bootstrap-progressbar/bootstrap-progressbar.min.js'
import  'iCheck/icheck.min.js'
import  'skycons/skycons.js'
import  'Flot/jquery.flot.js'
import  'Flot/jquery.flot.pie.js'
import  'Flot/jquery.flot.time.js'
import  'Flot/jquery.flot.stack.js'
import  'Flot/jquery.flot.resize.js'
import  'flot-orderbars/js/jquery.flot.orderBars.js'
import  'flot-spline/js/jquery.flot.spline.min.js'
import  'flot.curvedlines/curvedLines.js'
import  '../../public/js/date.js'
import  'jqvmap/dist/jquery.vmap.js'
import  'jqvmap/dist/maps/jquery.vmap.world.js'
import  'jqvmap/examples/js/jquery.vmap.sampledata.js'
import  'moment'
import  'bootstrap-daterangepicker/daterangepicker.js'

var moment = require('moment');
global.$ = global.jQuery = require('jquery');
